version: '3.8'

services:
  db:
    image: postgres
    container_name: db_restaurant_sys_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurante_sys
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    
  system:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src/uploads:/app/uploads
    restart: always

volumes:
  db_data:
