version: '3.8'

services:
  db:
    image: postgres
    container_name: db_restaurant_sys_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: always

  system:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src/uploads:/app/uploads
    restart: always

