services:
  system:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src/uploads:/app/uploads

  db:
    image: postgres
    container_name: db_restaurant_sys_container
    environment:
      - POSTGRES_USER=restaurant_sys
      - POSTGRES_PASSWORD=Res@sys27
      - POSTGRES_DB=restaurant_sys
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant_sys"]
      interval: 10s
      timeout: 5s
      retries: 5